# hugo 基本配置
baseURL = 'https://zhaocheney.github.io/'
languageCode = 'zh-cn'
title = 'zhaocheney'
theme = 'cleanwhite'

# 文章分页配置
paginate = 20

# markdown 渲染配置
[markup]
## markdown 转 HTML 渲染器, 默认 goldmark
defaultMarkdownHandler = 'goldmark'
## 文章目录配置
[markup.tableOfContents]
### 目录等级显示范围
startLevel = 1
endLevel = 2
## 代码高亮配置
[markup.highlight]
### 代码主题
style = 'vs'
### 是否显示行号
lineNos = true
### 是否使用 table 形式显示行号
lineNumbersInTable = false

# hugo-theme-cleanwhite 配置
[params]
## 顶部图片
header_image = '/img/header-image.jpg'
## 副标题, 标签栏显示为 {title} | {SEOTitle}
SEOTitle = 'zhaocheney'
## 标语
slogan = 'This Is Slogan'
## 搜索引擎检索关键字
keyword = '博客, 个人网站, 互联网, Java, Microservice, 微服务'

## 404 页面配置
title_404 = '哎呀！页面走丢了！～'
image_404 = '/images'

## 文章打赏配置
### 是否显示打赏
reward = true
### 打赏文字
reward_guide = '如果这篇文章对你有用, 请随意打赏'

## 顶部导航栏配置
### 是否隐藏分类菜单
omit_categories = false

## 底部信息配置
### 是否显示主题来源
upstreamAttribution = false

## 侧边栏配置
### 是否显示关于信息
about_me = true
### 关于信息头像
sidebar_avatar = '/img/avatar.jpg'
### 关于信息描述
sidebar_about_description = 'Software Developer'
### 是否显示标签
featured_tags = true
### 标签显示条件: 当 tag 在 POST 计数 > featured_condition_size 时, 显示该 tag
featured_condition_size = 0
### 是否显示收藏
bookmarks = true
### 是否显示好友
friends = true

## 顶部导航栏-扩展菜单
#[[params.addtional_menus]]
#title = '技术'
#href = '/categories/tech'
#[[params.addtional_menus]]
#title = '笔记'
#href = '/categories/notes'
[[params.addtional_menus]]
title = '归档'
href = '/archive'
[[params.addtional_menus]]
title = '关于'
href = '/about'

## 侧边栏-社交属性
[params.social]
email = 'zhaocheney@163.com'
wechat = '/img/avatar.jpg'
github = 'https://github.com/zhaocheney'

# 侧边栏-收藏列表
[[params.bookmark_link]]
title = 'Google'
href = 'https://www.google.com'
[[params.bookmark_link]]
title = 'InfoQ'
href = 'http://www.infoq.com/cn/'

# 侧边栏-好友列表
[[params.friend_link]]
title = 'Martin Fowler'
href = 'https://martinfowler.com'
[[params.friend_link]]
title = 'Martin Fowler'
href = 'https://martinfowler.com'

### 侧边栏-出版物列表
#[params.publications]
#title = '出版物'
#[[params.publications.items]]
#title = '出版物1'
#image = '/img/avatar.jpg'
#href = '/publications1'
#[[params.publications.items]]
#title = '出版物2'
#image = '/img/avatar.jpg'
#href = '/publications2'
